### ISSUE TITLE
Import Error: No module named submission

### ISSUE THREAD

**Issue by sgang007** [mstampfer/Coursera-Stanford-ML-Python#1]
Since the submission.py is not there in the environment path, the submit.py cannot be run in each of the excercises.

Please change the path before importing the submission.py in your code.

**Comment by mstampfer** [comment]
Added comment in README.md to set the PYTHONPATH environment variable before running script.

**Comment by samir2562** [comment]
hi there - still unclear to me what i need to do to run this file, i open exercise 1 in jupyter, go to execute the first lines of code and i get the error of no module named submission. How exactly do i fix that? Thanks

**Comment by samir2562** [comment]
> hi there - still unclear to me what i need to do to run this file, i open exercise 1 in jupyter, go to execute the first lines of code and i get the error of no module named submission. How exactly do i fix that? Thanks

resolved this by creating PYTHONPATH environment variable. Note i didnt see this in the README doc.
