### ISSUE TITLE
No option for entering the submission token

### ISSUE THREAD

**Issue by sgang007** [mstampfer/Coursera-Stanford-ML-Python#2]
To properly submit the assignments, you need to use the submission token. Many users dont use a password if they login with facebook. 
The way of submitting the assignments is with the email and token.
See the submitwithConfiguration.m file in the assignments.

This is the error shown while submtting.

```
File "submit.py", line 57, in <module>
    s.submit()
  File "/home/shubo/Desktop/Coursera-Stanford-ML-Python/Submission.py", line 37, in submit
    partFeedback = response['partFeedbacks'][part]
KeyError: 'partFeedbacks'
```

**Comment by mstampfer** [comment]
The user must enter the submission token when prompted and not his/her site password. I've changed the wording in Submission.py to correspond to the wording in submitWithConfiguration.m.

Try creating a 2 line file called token.txt and put it in the ex1 directory. The file contains your email address on the first line a and the submission token on the second line.  This file will be picked up so the user will not need to enter the submission token multiple times.
